### ISSUE TITLE
Provide visual affordance of mouseover the polygons

### ISSUE THREAD

**Issue by rgdonohue** [mjduever/acc-voting-districts#5]
The tooltip does offer this somewhat but may be nice to adjust the layer opacity or change the stroke in some way to further reinforce this interaction.

**Comment by mjduever** [comment]
I changed the stroke to yellow, but it doesn't return to the original colors on mouse out. I just tried it on the precinct layer and I have it commented out at the moment. I'm not sure how to return to the original color with how I assigned color in the first place....

**Comment by mjduever** [comment]
I added layer opacity instead.
